### ISSUE TITLE
 No backend sub-module imported

### ISSUE THREAD

**Issue by sxhfut** [aigamedev/scikit-neuralnetwork#90]
Traceback (most recent call last):
  File "/Users/sunxiao/PycharmProjects/testscikit/testscikit.py", line 116, in <module>
    clf.fit(train_X, train_y)
  File "/Users/sunxiao/myproject/scikit-neuralnetwork/sknn/mlp.py", line 259, in fit
    return super(Classifier, self)._fit(X, yp)
  File "/Users/sunxiao/myproject/scikit-neuralnetwork/sknn/mlp.py", line 129, in _fit
    X, y = self._initialize(X, y)
  File "/Users/sunxiao/myproject/scikit-neuralnetwork/sknn/mlp.py", line 42, in _initialize
    self._backend = MultiLayerPerceptronBackend(self)
  File "/Users/sunxiao/myproject/scikit-neuralnetwork/sknn/backend/__init__.py", line 12, in __init__
    raise NotImplementedError("No backend sub-module imported.")
NotImplementedError: No backend sub-module imported.

Process finished with exit code 1

**Comment by sxhfut** [comment]
fixed after pip --upgrade scikit-neuralnetwork

**Comment by alexjc** [comment]
This needs to be fixed in the `master` branch, you just downgraded.  Here's the workaround:

```
from sknn.backend import pylearn2
```

Also needs some documentation, I will leave this open as a reference until it's fixed in 0.3.

**Comment by rmkemker** [comment]
I am getting this error when I try to build a single AutoEncoder.  Lasagne built correctly with sknn during the pip install, but I am still getting this error.  Any thoughts on how to fix it?  I am using Ubuntu 14.04.

**Comment by alexjc** [comment]
There is no auto-encoder implemented in the latest release for Lasagne. #129

You need to go back to 0.4 for the PyLearn2 version, but that backend is not very well maintained and had many bugs.

**Comment by tgsmith61591** [comment]
So, is there any plan to tie the current AutoEncoder into any backend, or is it going to just be unusable for the forseeable future?
